# GDAL3 - python3
# registry.dpi.inpe.br/brazildatacube/geo:0.3

FROM brazildatacube/base:0.1
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    software-properties-common && \
    rm -rf /var/lib/apt/lists/*
RUN add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable && \
    apt-get update && \
    apt-get install -y \
    gdal-bin libgdal-dev && \
    rm -rf /var/lib/apt/lists/*
    
RUN pip3 install GDAL==3.0.2